// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskDb.Infrastructure.Data;

#nullable disable

namespace TaskDb.Infrastructure.Migrations
{
    [DbContext(typeof(TaskDbContext))]
    partial class TaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TaskDb.Domain.Entities.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsKeyAchievement")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ReportVersionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportVersionId");

                    b.ToTable("achievements", (string)null);
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.Blocker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsKeyIssue")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ReportVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ReportVersionId");

                    b.ToTable("blockers", (string)null);
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("int");

                    b.Property<string>("HrReviewComment")
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WeekEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.ReportAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int>("ReportVersionId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.HasIndex("ReportVersionId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("report_actions", (string)null);
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.ReportLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReportVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ReportVersionId");

                    b.ToTable("report_links", (string)null);
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.ReportVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NextWeekTasks")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OptionalNotes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("WeekEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ReportId");

                    b.ToTable("report_versions", (string)null);
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ActualHours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("ActualPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Deliverable")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PlannedHours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PlannedPercentage")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ReportVersionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TaskTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportVersionId");

                    b.HasIndex("TaskTypeId");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.TaskType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("task_types", (string)null);
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.UserProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("user_projects", (string)null);
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.WorkHour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ReportVersionId")
                        .HasColumnType("int");

                    b.Property<int>("TaskTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportVersionId");

                    b.HasIndex("TaskTypeId");

                    b.ToTable("work_hours", (string)null);
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.Achievement", b =>
                {
                    b.HasOne("TaskDb.Domain.Entities.ReportVersion", "ReportVersion")
                        .WithMany("Achievements")
                        .HasForeignKey("ReportVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportVersion");
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.Blocker", b =>
                {
                    b.HasOne("TaskDb.Domain.Entities.ReportVersion", "ReportVersion")
                        .WithMany("Blockers")
                        .HasForeignKey("ReportVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportVersion");
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.Report", b =>
                {
                    b.HasOne("TaskDb.Domain.Entities.Project", "Project")
                        .WithMany("Reports")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskDb.Domain.Entities.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.ReportAction", b =>
                {
                    b.HasOne("TaskDb.Domain.Entities.Report", "Report")
                        .WithMany("Actions")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskDb.Domain.Entities.ReportVersion", "ReportVersion")
                        .WithMany("Actions")
                        .HasForeignKey("ReportVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskDb.Domain.Entities.User", "Reviewer")
                        .WithMany("ReportActions")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");

                    b.Navigation("ReportVersion");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.ReportLink", b =>
                {
                    b.HasOne("TaskDb.Domain.Entities.ReportVersion", "ReportVersion")
                        .WithMany("Links")
                        .HasForeignKey("ReportVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportVersion");
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.ReportVersion", b =>
                {
                    b.HasOne("TaskDb.Domain.Entities.Project", "Project")
                        .WithMany("ReportVersions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskDb.Domain.Entities.Report", "Report")
                        .WithMany("Versions")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Report");
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("TaskDb.Domain.Entities.ReportVersion", "ReportVersion")
                        .WithMany("Tasks")
                        .HasForeignKey("ReportVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskDb.Domain.Entities.TaskType", "TaskType")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportVersion");

                    b.Navigation("TaskType");
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.User", b =>
                {
                    b.HasOne("TaskDb.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.UserProject", b =>
                {
                    b.HasOne("TaskDb.Domain.Entities.Project", "Project")
                        .WithMany("UserProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskDb.Domain.Entities.User", "User")
                        .WithMany("UserProjects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.WorkHour", b =>
                {
                    b.HasOne("TaskDb.Domain.Entities.ReportVersion", "ReportVersion")
                        .WithMany("WorkHours")
                        .HasForeignKey("ReportVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskDb.Domain.Entities.TaskType", "TaskType")
                        .WithMany("WorkHours")
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportVersion");

                    b.Navigation("TaskType");
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.Project", b =>
                {
                    b.Navigation("ReportVersions");

                    b.Navigation("Reports");

                    b.Navigation("UserProjects");
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.Report", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.ReportVersion", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("Actions");

                    b.Navigation("Blockers");

                    b.Navigation("Links");

                    b.Navigation("Tasks");

                    b.Navigation("WorkHours");
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.TaskType", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("WorkHours");
                });

            modelBuilder.Entity("TaskDb.Domain.Entities.User", b =>
                {
                    b.Navigation("ReportActions");

                    b.Navigation("Reports");

                    b.Navigation("UserProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
